import Icon from '@/components/shared/Icon';
import AhfDrawing from '@/components/drawings/AhfDrawing';
import Blueprint from '@/components/behaviour/Blueprint';

// The exploded AHF blueprint. The drawing is generated by tools/draw-ahf.mjs.
export default function ActiveHarmonicFilter() {
  return (
    <section className="ahf on-ink" id="ahf" aria-labelledby="ahf-title">
      <div className="ahf__track">
        <div className="ahf__stage wrap">
          <div className="ahf__text">
            <h2 className="ahf__title" id="ahf-title">Active Harmonic Filter</h2>
            <p className="ahf__std">IEEE 519 · Harmonic Control in Electric Power Systems</p>
            <p className="ahf__intro">An active harmonic filter (AHF) is a type of harmonic filter that uses active components, such as transistors and capacitors, to reduce harmonic current distortion on an electrical system. It can be used in industrial and commercial installations to eliminate harmonic current distortion and improve the efficiency of the system.</p>
            <ol className="callouts">
              <li className="callout" data-step="1">
                <h3 className="callout__title">Upper PCBA auxiliary air duct design</h3>
                <p>Expansion of the heat dissipation channel for wide angle heat dissipation.</p>
              </li>
              <li className="callout" data-step="2">
                <h3 className="callout__title">IGBT PCBA precision components</h3>
                <p>An AHF uses active components to detect and then neutralize harmonic current distortion.</p>
              </li>
              <li className="callout" data-step="3">
                <h3 className="callout__title">Inductors and IGBT heatsink: around 90% of the heat</h3>
                <p>The IGBT heatsink and inductors, which account for most of the heat of the AHF, are concentrated in the lower layer with forced air cooling for fast heat dissipation, and do not affect the upper PCBA.</p>
              </li>
            </ol>
            <button className="text-link" type="button" data-product="ahf">Active Harmonic Filter · AHF and AHF Pro <Icon name="arrow" /></button>
          </div>
          <figure className="ahf__figure">
            <AhfDrawing />
            <figcaption className="ahf__caption">Layered structure design for higher reliability</figcaption>
          </figure>
        </div>
      </div>
      <Blueprint section="ahf" />
    </section>
  );
}
