import Icon from '@/components/shared/Icon';
import HeatPumpDrawing from '@/components/drawings/HeatPumpDrawing';
import Blueprint from '@/components/behaviour/Blueprint';

// Same blueprint as the AHF, mirrored. The drawing is generated by tools/draw-heat-pump.mjs.
export default function HeatPump() {
  return (
    <section className="ahf ahf--flip on-ink" id="heat-pump" aria-labelledby="hp-title">
      <div className="ahf__track">
        <div className="ahf__stage wrap">
          <div className="ahf__text">
            <h2 className="ahf__title" id="hp-title">Heat Pumps System</h2>
            <p className="ahf__std">Replaces boilers/calorifiers · Energy cost savings</p>
            <p className="ahf__intro">A heat pump is a device that transfers heat energy from a source of heat to what is called a thermal reservoir. Heat pumps are used to provide heating, cooling, and hot water to buildings in the form of space heating, air conditioning, and domestic hot water.</p>
            <ol className="callouts">
              <li className="callout" data-step="1">
                <h3 className="callout__title">Free secondary source: heating or cooling</h3>
                <p>Heat pumps can be used to cool as well as heat a space and are often used as an energy efficient alternative to furnaces and air conditioners.</p>
              </li>
              <li className="callout" data-step="2">
                <h3 className="callout__title">Higher co-efficient of performance (COP)</h3>
                <p>Heat pumps transfer heat by circulating a refrigerant through a cycle of evaporation and condensation.</p>
              </li>
              <li className="callout" data-step="3">
                <h3 className="callout__title">Simultaneous heating and cooling</h3>
                <p>Domestic hot water generation alongside cold water generation integrated in the chilled water circuit.</p>
              </li>
            </ol>
            <button className="text-link" type="button" data-product="heat-pump">Heat Pumps System <Icon name="arrow" /></button>
          </div>
          <figure className="ahf__figure">
            <HeatPumpDrawing />
            <figcaption className="ahf__caption">Hot water <span className="ahf__key ahf__key--hot" aria-hidden="true" /> and chilled water <span className="ahf__key ahf__key--cold" aria-hidden="true" /> connections</figcaption>
          </figure>
        </div>
      </div>
      <Blueprint section="heat-pump" />
    </section>
  );
}
