// Shared by draw-ahf.mjs and draw-heat-pump.mjs: writes a generated SVG drawing as a React component
// in components/drawings/. The drawings only use class, style (custom properties), data-* and plain
// SVG attributes, so the JSX conversion is a few renames.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function toJsx(svg) {
  return svg
    .replace(/ class="/g, ' className="')
    .replace(/ style="([^"]*)"/g, (_, css) => ' style={{ ' + css.split(';').filter(Boolean).map(d => {
      const i = d.indexOf(':');
      return `'${d.slice(0, i).trim()}': '${d.slice(i + 1).trim()}'`;
    }).join(', ') + ' }}')
    .replace(/>([^<]*)</g, (_, text) => '>' + text.replace(/[{}>]/g, c => ({ '{': '&#123;', '}': '&#125;', '>': '&gt;' })[c]) + '<');
}

export function writeDrawing(name, svg, script) {
  const file = join(root, 'components', 'drawings', name + '.jsx');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `// Generated by tools/${script}. Do not edit by hand: change the script and run it again.\n` +
    `export default function ${name}() {\n  return (\n    ${toJsx(svg)}\n  );\n}\n`);
  return file;
}
